# Specifying the base image
FROM python:3.12-bullseye

# Install system dependencies and pip
RUN apt-get update -y && apt-get install --no-install-recommends -y \
    python3-pip

RUN apt install nano -y

# Installing the requirements.txt
RUN pip install --upgrade pip
